name: main

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests module
        run: pip3 install requests


      - name: Test
        run: make test

      - name: Benchmark Linux
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get install -y siege
            siege --version
            make benchmark
          fi

      - name: Benchmark Macos
        run: |
          if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            sudo sysctl -w net.inet.tcp.msl=1000
            brew install siege
            siege --version
            make benchmark
          fi
