name: main

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests module
        run: pip3 install requests


      - name: Test
        run: make test

      - name: Benchmark
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt update && sudo apt install siege;
            siege --version;
            make benchmark;
          fi
